toc:
- name: Background
  description: |
    The extension background context manages the sitemap generation process.
  children:
    - backgroundEvents
    - sitemapGenerator
    - centeredWindow

- name: Client-Side Crawler
  description: |
    The crawler is responsible for finding urls in in the crawled documents.
  children:
    - crawler

- name: User Interface
  description: |
    The UI pages are extension pages allowing user to control the sitemap generation process and interaction with the sitemap generator.
    
    There are currectly two views: 
    - `Setup` - page where user can configure their preferences
    - `Processing` - page shows while sitemap generation is in progress

  children:
    - setup
    - processing